# Generated by Django 6.0.6 on 2026-07-17 18:45

import django.db.models.deletion
import partituras.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actividades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('compositor', models.CharField(blank=True, max_length=200)),
                ('parte', models.CharField(blank=True, help_text='Ej: Clarinete 2', max_length=100)),
                ('archivo_original', models.FileField(upload_to=partituras.models._upload_path_original)),
                ('archivo_normalizado', models.FileField(blank=True, null=True, upload_to=partituras.models._upload_path_normalizado)),
                ('estado_normalizacion', models.CharField(choices=[('pendiente', 'Pendiente'), ('propuesta', 'Propuesta'), ('confirmada', 'Confirmada')], default='pendiente', max_length=12)),
                ('estado_analisis', models.CharField(choices=[('pendiente', 'Pendiente'), ('propuesto', 'Propuesto'), ('confirmado', 'Confirmado')], default='pendiente', max_length=12)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('instrumento', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partituras', to='actividades.instrumento')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partituras', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partitura',
                'verbose_name_plural': 'Partituras',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('rotacion_detectada', models.IntegerField(default=0)),
                ('rotacion_aplicada', models.IntegerField(default=0)),
                ('angulo_deskew_detectado', models.FloatField(default=0)),
                ('angulo_deskew_aplicado', models.FloatField(default=0)),
                ('confirmada', models.BooleanField(default=False)),
                ('partitura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paginas', to='partituras.partitura')),
            ],
            options={
                'verbose_name': 'Página',
                'verbose_name_plural': 'Páginas',
                'ordering': ['numero'],
                'unique_together': {('partitura', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField()),
                ('origen', models.CharField(choices=[('auto', 'Automático'), ('manual', 'Manual')], default='auto', max_length=10)),
                ('pagina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sistemas', to='partituras.pagina')),
            ],
            options={
                'verbose_name': 'Sistema',
                'verbose_name_plural': 'Sistemas',
                'ordering': ['pagina__numero', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Compas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('origen', models.CharField(choices=[('auto', 'Automático'), ('manual', 'Manual')], default='auto', max_length=10)),
                ('confirmado', models.BooleanField(default=False)),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compases', to='partituras.sistema')),
            ],
            options={
                'verbose_name': 'Compás',
                'verbose_name_plural': 'Compases',
                'ordering': ['sistema__pagina__numero', 'sistema__orden', 'x'],
            },
        ),
    ]
