# Generated by Django 6.0.6 on 2026-07-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partituras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistema',
            name='confirmado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sistema',
            name='height',
            field=models.FloatField(default=0.0, help_text='Alto relativo (0-1)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sistema',
            name='y',
            field=models.FloatField(default=0.0, help_text='Posición vertical relativa (0-1) del borde superior'),
            preserve_default=False,
        ),
    ]
