# Generated by Django 6.0.6 on 2026-07-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partituras', '0002_sistema_confirmado_sistema_height_sistema_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagina',
            name='margen_x0_aplicado',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='pagina',
            name='margen_x0_detectado',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='pagina',
            name='margen_x1_aplicado',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='pagina',
            name='margen_x1_detectado',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='pagina',
            name='margen_y0_aplicado',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='pagina',
            name='margen_y0_detectado',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='pagina',
            name='margen_y1_aplicado',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='pagina',
            name='margen_y1_detectado',
            field=models.FloatField(default=1.0),
        ),
    ]
