# Generated by Django 6.0.6 on 2026-07-18 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partituras', '0003_pagina_margen_x0_aplicado_pagina_margen_x0_detectado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagina',
            name='ancla_confirmada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pagina',
            name='ancla_x0',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagina',
            name='ancla_x1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagina',
            name='ancla_y0',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagina',
            name='ancla_y1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagina',
            name='ignorada',
            field=models.BooleanField(default=False, help_text='Página en blanco, portada, etc. — se excluye del análisis.'),
        ),
    ]
