# Generated by Django 6.0.6 on 2026-07-18 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partituras', '0004_pagina_ancla_confirmada_pagina_ancla_x0_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagina',
            name='ancla_linea_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagina',
            name='ancla_linea_y0',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagina',
            name='ancla_linea_y1',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
