# Generated by Django 6.0.6 on 2026-07-18 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partituras', '0005_pagina_ancla_linea_x_pagina_ancla_linea_y0_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagina',
            name='barras_confirmadas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pagina',
            name='margen_confirmado',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Barra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(help_text='Posición horizontal relativa (0-1) de la página')),
                ('estado', models.CharField(choices=[('dudosa', 'Dudosa'), ('aceptada', 'Aceptada')], default='dudosa', max_length=10)),
                ('origen', models.CharField(choices=[('auto', 'Automático'), ('manual', 'Manual')], default='auto', max_length=10)),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barras', to='partituras.sistema')),
            ],
            options={
                'verbose_name': 'Barra',
                'verbose_name_plural': 'Barras',
                'ordering': ['sistema__pagina__numero', 'sistema__orden', 'x'],
            },
        ),
    ]
