# Generated by Django 6.0.6 on 2026-07-18 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partituras', '0006_pagina_barras_confirmadas_pagina_margen_confirmado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagina',
            name='compases_confirmados',
            field=models.BooleanField(default=False),
        ),
    ]
