# Generated by Django 6.0.6 on 2026-07-18 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partituras', '0007_pagina_compases_confirmados'),
    ]

    operations = [
        migrations.AddField(
            model_name='compas',
            name='repeticiones',
            field=models.PositiveIntegerField(default=1, help_text='Cuántos compases reales representa éste — 1 en el caso normal; más de 1 para un silencio de varios compases marcado a mano por el usuario (no se detecta automáticamente). El siguiente compás numera desde numero + repeticiones, no siempre numero + 1.'),
        ),
    ]
