# Generated by Django 6.0.6 on 2026-07-19 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partituras', '0008_compas_repeticiones'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('compositor', models.CharField(blank=True, max_length=200)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obras', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Obra',
                'verbose_name_plural': 'Obras',
                'ordering': ['-creado'],
            },
        ),
        migrations.AddField(
            model_name='partitura',
            name='obra',
            field=models.ForeignKey(blank=True, help_text='La obra a la que pertenece esta parte, si ya se agrupó — separarla no borra la partitura.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partituras', to='partituras.obra'),
        ),
    ]
