# Generated by Django 6.0.6 on 2026-07-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partituras', '0009_obra_partitura_obra'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='arreglista',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
