# Generated by Django 6.0.6 on 2026-07-19 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partituras', '0010_obra_arreglista'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segmento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(help_text='Numerar de a 10 (10, 20, 30…) para poder insertar filas en el medio sin renumerar el resto.')),
                ('compas_desde', models.PositiveIntegerField(blank=True, help_text='Vacío sólo en la fila final de cierre (sin contenido propio, sólo marca dónde termina el último compás).', null=True)),
                ('pulso_desde', models.PositiveIntegerField(default=1)),
                ('compas_hasta', models.PositiveIntegerField(blank=True, null=True)),
                ('pulso_hasta', models.PositiveIntegerField(blank=True, help_text='Vacío = hasta el final del último pulso del compás.', null=True)),
                ('indicacion_compas', models.CharField(blank=True, help_text='Ej: 4/4 — vacío hereda la de la fila anterior.', max_length=10)),
                ('variacion_tempo', models.CharField(blank=True, choices=[('', 'Constante'), ('accelerando', 'Accelerando'), ('ritardando', 'Ritardando')], default='', max_length=12)),
                ('bpm', models.PositiveIntegerField(blank=True, help_text='Tempo editorial (el que indica la partitura) — todavía no se usa para nada, sólo se guarda.', null=True)),
                ('descripcion', models.CharField(blank=True, help_text="Rótulo libre (ej: 'Exposición', 'Coda') — sin efecto en la secuencia.", max_length=200)),
                ('tiempo_inicio', models.DurationField(blank=True, help_text='Tiempo transcurrido desde el inicio de la grabación hasta acá — vacío hasta sincronizar con audio/video real.', null=True)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segmentos', to='partituras.obra')),
            ],
            options={
                'verbose_name': 'Segmento',
                'verbose_name_plural': 'Segmentos',
                'ordering': ['obra', 'orden'],
                'unique_together': {('obra', 'orden')},
            },
        ),
    ]
