# Generated by Django 6.0.6 on 2026-07-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partituras', '0011_segmento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segmento',
            name='pulso_desde',
            field=models.PositiveIntegerField(blank=True, help_text='Vacío = 1 (el primer pulso) — se resuelve así al leer, nunca se guarda el 1 explícito.', null=True),
        ),
        migrations.AlterField(
            model_name='segmento',
            name='pulso_hasta',
            field=models.PositiveIntegerField(blank=True, help_text='Vacío = hasta el final del último pulso del compás — se resuelve así al leer.', null=True),
        ),
    ]
