# Generated by Django 6.0.6 on 2026-07-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partituras', '0012_alter_segmento_pulso_desde_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='segmento',
            name='bpm_llegada',
            field=models.PositiveIntegerField(blank=True, help_text='Sólo tiene sentido en un tramo con accelerando/ritardando: tempo al que llega al final. Es lo que hereda la fila siguiente (no el bpm de arranque) cuando está presente.', null=True),
        ),
        migrations.AddField(
            model_name='segmento',
            name='duracion_fija',
            field=models.DurationField(blank=True, help_text='Duración fija de este tramo (p.ej. un calderón) — si se completa, reemplaza el cálculo normal por tempo para este tramo en vez de bpm/bpm_llegada.', null=True),
        ),
        migrations.AlterField(
            model_name='segmento',
            name='bpm',
            field=models.PositiveIntegerField(blank=True, help_text='Tempo de arranque de este tramo (constante, o punto de partida si es accelerando/ritardando) — vacío hereda el tempo vigente (bpm_llegada si la fila anterior tenía uno, si no su bpm) de la fila anterior. Editorial, todavía no se usa para calcular nada.', null=True),
        ),
    ]
