# Generated by Django 6.0.6 on 2026-07-19 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partituras', '0013_segmento_bpm_llegada_segmento_duracion_fija_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segmento',
            name='duracion_fija',
        ),
    ]
