# Generated by Django 6.0.6 on 2026-07-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partituras', '0014_remove_segmento_duracion_fija'),
    ]

    operations = [
        migrations.AddField(
            model_name='segmento',
            name='desde_texto',
            field=models.CharField(blank=True, help_text='Lo que se tipea en la tabla: "4" (compás 4, pulso 1) o "4,1.5" (compás 4, pulso 1 y medio) — coma separa compás de pulso, punto es el decimal DENTRO del pulso.', max_length=20),
        ),
        migrations.AddField(
            model_name='segmento',
            name='hasta_texto',
            field=models.CharField(blank=True, help_text='Igual que desde_texto, pero "4" sin coma acá significa "hasta el final del compás 4", no pulso 1.', max_length=20),
        ),
        migrations.AddField(
            model_name='segmento',
            name='tiempo_inicio_calculado',
            field=models.DurationField(blank=True, help_text='Estimación a partir de bpm/bpm_llegada de cada tramo (no de una grabación real) — se recalcula solo cada vez que se guarda el itinerario, queda como referencia independiente de tiempo_inicio.', null=True),
        ),
        migrations.AlterField(
            model_name='segmento',
            name='bpm',
            field=models.PositiveIntegerField(blank=True, help_text='Tempo de arranque de este tramo (constante, o punto de partida si es accelerando/ritardando) — vacío hereda el tempo vigente (bpm_llegada si la fila anterior tenía uno, si no su bpm) de la fila anterior. Se usa para calcular tiempo_inicio_calculado.', null=True),
        ),
        migrations.AlterField(
            model_name='segmento',
            name='pulso_desde',
            field=models.FloatField(blank=True, help_text='Vacío = 1 (el primer pulso) — se resuelve así al leer, nunca se guarda el 1 explícito. Puede ser decimal (1.5 = la corchea después del primer pulso).', null=True),
        ),
        migrations.AlterField(
            model_name='segmento',
            name='pulso_hasta',
            field=models.FloatField(blank=True, help_text='Vacío = hasta el final del último pulso del compás — se resuelve así al leer. También puede ser decimal.', null=True),
        ),
    ]
