# Generated by Django 6.0.6 on 2026-07-21 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partituras', '0015_segmento_desde_texto_segmento_hasta_texto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenciaObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desde_compas', models.CharField(blank=True, max_length=20)),
                ('desde_pasada', models.PositiveIntegerField(default=1)),
                ('hasta_compas', models.CharField(blank=True, max_length=20)),
                ('hasta_pasada', models.PositiveIntegerField(default=1)),
                ('loop', models.BooleanField(default=False)),
                ('velocidad', models.PositiveIntegerField(default=100)),
                ('compases_al_aire', models.PositiveIntegerField(default=1)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias_usuario', to='partituras.obra')),
                ('parte_seguida', models.ForeignKey(blank=True, help_text="Última parte elegida explícitamente en el selector — desempata antes que 'mi propia parte'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='partituras.partitura')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias_obra', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferencia de obra',
                'verbose_name_plural': 'Preferencias de obra',
                'unique_together': {('usuario', 'obra')},
            },
        ),
        migrations.CreateModel(
            name='PreferenciaParte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_zoom', models.FloatField(default=1.0)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('partitura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias_usuario', to='partituras.partitura')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias_parte', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferencia de parte',
                'verbose_name_plural': 'Preferencias de parte',
                'unique_together': {('usuario', 'partitura')},
            },
        ),
    ]
