# Generated by Django 6.0.6 on 2026-07-21 11:22

import partituras.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partituras', '0016_preferenciaobra_preferenciaparte'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='audio',
            field=models.FileField(blank=True, help_text='Grabación de referencia (mp3) para sincronizar el itinerario — ver Segmento.tiempo_inicio y la pantalla de sincronización.', null=True, upload_to=partituras.models._upload_path_audio),
        ),
    ]
