# Generated by Django 6.0.6 on 2026-07-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partituras', '0017_obra_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferenciaobra',
            name='ejecutar_con_audio',
            field=models.BooleanField(default=False, help_text='Si la ejecución sigue el audio de referencia (tiempos reales, velocidad fija) en vez del reloj calculado — ver sincronizar_audio. Se recuerda igual que el resto de estas preferencias.'),
        ),
    ]
