# Generated by Django 6.0.6 on 2026-07-21 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partituras', '0018_preferenciaobra_ejecutar_con_audio'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarcaTiempoCompas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compas', models.PositiveIntegerField()),
                ('pasada', models.PositiveIntegerField(default=1)),
                ('tiempo_inicio', models.DurationField()),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcas_tiempo_compas', to='partituras.obra')),
            ],
            options={
                'verbose_name': 'Marca de tiempo de compás',
                'verbose_name_plural': 'Marcas de tiempo de compás',
                'ordering': ['obra', 'compas', 'pasada'],
                'unique_together': {('obra', 'compas', 'pasada')},
            },
        ),
    ]
