# Generated by Django 6.0.6 on 2026-07-21 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partituras', '0019_marcatiempocompas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partitura',
            name='compositor',
        ),
    ]
