# Generated by Django 6.0.6 on 2026-07-23 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partituras', '0020_remove_partitura_compositor'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferenciaobra',
            name='fuente_temporizacion',
            field=models.CharField(choices=[('itinerario', 'Itinerario'), ('compases', 'Compases')], default='compases', help_text="Qué fuente de tiempos reales gobierna el cursor/sombreado durante la ejecución: 'itinerario' usa sólo Segmento.tiempo_inicio (con tiempo_inicio_calculado como base siempre disponible, ver sincronizar_itinerario); 'compases' usa sólo MarcaTiempoCompas (sin caer al cálculo puro fuera del tramo cubierto, ver sincronizar_compases). Es independiente de ejecutar_con_audio (ese controla si SUENA el audio de referencia, esto controla de qué reloj sale la posición del cursor).", max_length=12),
        ),
        migrations.AlterField(
            model_name='preferenciaobra',
            name='ejecutar_con_audio',
            field=models.BooleanField(default=False, help_text='Si la ejecución sigue el audio de referencia (tiempos reales, velocidad fija) en vez del reloj calculado — ver sincronizar_itinerario. Se recuerda igual que el resto de estas preferencias.'),
        ),
    ]
