# Generated by Django 6.0.6 on 2026-07-24 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partituras', '0021_preferenciaobra_fuente_temporizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marcatiempocompas',
            name='explicita',
            field=models.BooleanField(default=True, help_text='True si la puso el usuario (tap, edición manual, desplazamiento en bloque); False si la generó la interpolación de sincronizar_compases — esas no sirven de ancla para futuras interpolaciones, y se muestran atenuadas.'),
        ),
    ]
