# Generated by Django 6.0.6 on 2026-07-24 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partituras', '0022_marcatiempocompas_explicita'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partitura',
            name='archivo_normalizado',
        ),
    ]
