# Generated by Django 6.0.6 on 2026-07-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partituras', '0023_remove_partitura_archivo_normalizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='publicada',
            field=models.BooleanField(default=True, help_text='Si está en False, sólo el dueño y los admins la ven (en la biblioteca y entrando directo por URL) — el resto de los usuarios logueados no la ve en absoluto.'),
        ),
        migrations.AddField(
            model_name='preferenciaobra',
            name='modo_score',
            field=models.CharField(blank=True, choices=[('compas', 'Compás'), ('partitura', 'Partitura')], help_text='Modo compás vs. modo partitura en el navegador — en blanco significa que todavía no se guardó ninguna elección, y se usa el default viejo (ancho de pantalla) en su lugar.', max_length=10),
        ),
    ]
