# Generated by Django 6.0.6 on 2026-07-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partituras', '0024_obra_publicada_preferenciaobra_modo_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='actualizado',
            field=models.DateTimeField(auto_now=True, help_text='Se actualiza sola en cualquier cambio de la obra en sí (título, audio, publicada...), y también cuando cambia su itinerario (Segmento) o sus marcas de tiempo por compás (MarcaTiempoCompas) — ver signals.py, que la toca aparte porque son modelos distintos. NO cambia por preferencias de usuario (PreferenciaObra/PreferenciaParte) — esas son por-usuario, no un cambio real de la obra.'),
        ),
    ]
