# Generated by Django 6.0.6 on 2026-07-25 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partituras', '0025_obra_actualizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='partitura',
            name='publicada',
            field=models.BooleanField(default=True, help_text='Si está en False, sólo el dueño de la parte, el dueño de la obra a la que pertenece (si tiene) y los admins la ven — le da al dueño de la obra la potestad de aceptar o rechazar una parte que subió otro usuario.'),
        ),
    ]
