# Generated by Django 6.0.6 on 2026-07-26 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partituras', '0026_partitura_publicada'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarcaNotacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('compas', 'Indicación de compás'), ('armadura', 'Armadura'), ('tempo', 'Tempo')], max_length=10)),
                ('compas', models.PositiveIntegerField(help_text='A partir de este compás rige, hasta la próxima marca del mismo tipo.')),
                ('pasada', models.PositiveIntegerField(blank=True, help_text='Vacío = rige en cualquier pasada por este compás. Completo = override sólo para esa pasada puntual.', null=True)),
                ('valor', models.CharField(help_text='Según tipo: "4/4" (compás), "96" (tempo, en bpm), texto libre (armadura).', max_length=20)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcas_notacion', to='partituras.obra')),
            ],
            options={
                'verbose_name': 'Marca de notación',
                'verbose_name_plural': 'Marcas de notación',
                'ordering': ['obra', 'tipo', 'compas', 'pasada'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('pasada__isnull', True)), fields=('obra', 'tipo', 'compas'), name='unico_general_por_obra_tipo_compas'), models.UniqueConstraint(condition=models.Q(('pasada__isnull', False)), fields=('obra', 'tipo', 'compas', 'pasada'), name='unico_puntual_por_obra_tipo_compas_pasada')],
            },
        ),
    ]
