# Generated by Django 6.0.6 on 2026-07-26 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partituras', '0028_backfill_marcanotacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segmento',
            name='bpm',
        ),
        migrations.RemoveField(
            model_name='segmento',
            name='indicacion_compas',
        ),
    ]
