# Generated by Django 6.0.6 on 2026-07-26 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partituras', '0029_remove_segmento_bpm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistema',
            name='contenido_x0',
            field=models.FloatField(blank=True, help_text='Columna real (0-1) donde arranca el contenido de este sistema (clave/armadura) — a diferencia del margen de página, que es un dato de toda la página. Vacío si no se pudo detectar (sistema vacío): el primer compás cae al margen en ese caso.', null=True),
        ),
    ]
