# Generated by Django 6.0.6 on 2026-07-26 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partituras', '0030_sistema_contenido_x0'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistema',
            name='contenido_x1',
            field=models.FloatField(blank=True, help_text='Columna real (0-1) donde termina el contenido de este sistema, SÓLO cuando no coincide con la última barra aceptada (si coincide, esa barra ya cierra bien el compás y esto queda en None — no hace falta ningún límite virtual de cierre).', null=True),
        ),
    ]
