# Generated by Django 6.0.6 on 2026-07-26 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partituras', '0031_sistema_contenido_x1'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagina',
            name='umbral_contenido_sistema',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
