# Generated by Django 6.0.6 on 2026-07-27 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partituras', '0032_pagina_umbral_contenido_sistema'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Ciclo',
                'verbose_name_plural': 'Ciclos',
                'ordering': ['repertorio__nombre', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Repertorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Repertorio',
                'verbose_name_plural': 'Repertorios',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='obra',
            name='ciclo',
            field=models.ForeignKey(blank=True, help_text='Organización opcional de biblioteca (repertorio/ciclo) — no afecta la ejecución de la obra.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obras', to='partituras.ciclo'),
        ),
        migrations.AddField(
            model_name='ciclo',
            name='repertorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciclos', to='partituras.repertorio'),
        ),
        migrations.AlterUniqueTogether(
            name='ciclo',
            unique_together={('repertorio', 'nombre')},
        ),
    ]
