# Generated by Django 6.0.6 on 2026-07-27 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partituras', '0033_ciclo_repertorio_obra_ciclo_ciclo_repertorio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EfectoTempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('accelerando', 'Accelerando'), ('ritardando', 'Ritardando'), ('calderon', 'Calderón')], max_length=12)),
                ('desde_texto', models.CharField(help_text='Dónde arranca el efecto: "compás" (pulso 1) o "compás,pulso" (ej: "10,2.5").', max_length=20)),
                ('compas_desde', models.PositiveIntegerField()),
                ('pulso_desde', models.FloatField(blank=True, null=True)),
                ('hasta_texto', models.CharField(blank=True, help_text='Vacío en calderón. Dónde termina (accelerando/ritardando) — mismo formato que desde_texto.', max_length=20)),
                ('compas_hasta', models.PositiveIntegerField(blank=True, null=True)),
                ('pulso_hasta', models.FloatField(blank=True, null=True)),
                ('valor', models.CharField(help_text='Según tipo: bpm de llegada (accelerando/ritardando) o factor de duración (calderón, ej: "1.5").', max_length=20)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='efectos_tempo', to='partituras.obra')),
            ],
            options={
                'verbose_name': 'Efecto de tempo',
                'verbose_name_plural': 'Efectos de tempo',
                'ordering': ['obra', 'compas_desde', 'pulso_desde'],
            },
        ),
    ]
