# Generated by Django 6.0.6 on 2026-07-27 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partituras', '0035_backfill_efectotempo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segmento',
            name='bpm_llegada',
        ),
        migrations.RemoveField(
            model_name='segmento',
            name='variacion_tempo',
        ),
    ]
