# Generated by Django 6.0.6 on 2026-07-27 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partituras', '0036_remove_segmento_bpm_llegada_segmento_variacion_tempo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarcaTiempoPulso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compas', models.PositiveIntegerField()),
                ('pasada', models.PositiveIntegerField(default=1)),
                ('pulso', models.PositiveIntegerField()),
                ('tiempo_inicio', models.DurationField()),
                ('explicita', models.BooleanField(default=True)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcas_tiempo_pulso', to='partituras.obra')),
            ],
            options={
                'verbose_name': 'Marca de tiempo de pulso',
                'verbose_name_plural': 'Marcas de tiempo de pulso',
                'ordering': ['obra', 'compas', 'pasada', 'pulso'],
                'unique_together': {('obra', 'compas', 'pasada', 'pulso')},
            },
        ),
    ]
