# Generated by Django 6.0.6 on 2026-07-27 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partituras', '0037_marcatiempopulso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sistema',
            name='contenido_x0',
            field=models.FloatField(blank=True, help_text='Columna real (0-1) donde arranca el contenido de este sistema (clave/armadura) — a diferencia del margen de página, que es un dato de toda la página. Detectado automáticamente, pero también editable a mano desde Ajuste de barras (clic en la zona antes de la primera barra para reubicarlo, clic en la línea para descartarlo). Vacío si no se pudo detectar o si se descartó: el primer compás cae al margen en ese caso.', null=True),
        ),
        migrations.AlterField(
            model_name='sistema',
            name='contenido_x1',
            field=models.FloatField(blank=True, help_text='Columna real (0-1) donde termina el contenido de este sistema, SÓLO cuando no coincide con la última barra aceptada (si coincide, esa barra ya cierra bien el compás y esto queda en None — no hace falta ningún límite virtual de cierre). Igual que contenido_x0, también editable a mano desde Ajuste de barras.', null=True),
        ),
    ]
