# Generated by Django 6.0.6 on 2026-07-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partituras', '0038_alter_sistema_contenido_x0_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagina',
            name='umbral_separacion_sistemas',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
