# Generated by Django 6.0.6 on 2026-07-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partituras', '0039_pagina_umbral_separacion_sistemas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferenciaobra',
            name='fuente_temporizacion',
        ),
        migrations.AlterField(
            model_name='preferenciaobra',
            name='ejecutar_con_audio',
            field=models.BooleanField(default=False, help_text='Si la ejecución sigue el audio de referencia (tiempos reales, velocidad fija) en vez del reloj calculado. Se recuerda igual que el resto de estas preferencias.'),
        ),
        migrations.AlterField(
            model_name='segmento',
            name='tiempo_inicio',
            field=models.DurationField(blank=True, help_text="Tiempo real transcurrido desde el inicio de la grabación hasta acá — hoy sólo se usa en la fila de cierre (marca el fin real de la obra, ver 'Sincronizar compases'); vacío en el resto de las filas.", null=True),
        ),
    ]
