# Generated by Django 6.0.6 on 2026-07-30 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partituras', '0040_remove_preferenciaobra_fuente_temporizacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='efectotempo',
            name='tipo',
            field=models.CharField(choices=[('accelerando', 'Accelerando'), ('ritardando', 'Ritardando'), ('calderon', 'Calderón'), ('pausa', 'Pausa')], max_length=12),
        ),
        migrations.AlterField(
            model_name='efectotempo',
            name='valor',
            field=models.CharField(help_text='Según tipo: bpm de llegada (accelerando/ritardando), factor de duración (calderón, ej: "1.5") o duración estimada en segundos (pausa, ej: "8").', max_length=20),
        ),
    ]
