# Generated by Django 6.0.6 on 2026-07-30 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partituras', '0041_alter_efectotempo_tipo_alter_efectotempo_valor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anotacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compas', models.PositiveIntegerField(help_text='Compás al que está anclada — el más cercano al punto donde se hizo clic.')),
                ('tipo', models.CharField(choices=[('texto', 'Texto')], default='texto', max_length=10)),
                ('posicion', models.CharField(choices=[('arriba', 'Arriba del pentagrama'), ('abajo', 'Abajo del pentagrama')], default='arriba', max_length=10)),
                ('texto', models.TextField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anotaciones', to='partituras.obra')),
                ('partitura', models.ForeignKey(blank=True, help_text='Vacío = de obra (para cualquier parte). Con parte y sin usuario = de esa parte. Con parte Y usuario = privada de ese usuario.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anotaciones', to='partituras.partitura')),
                ('usuario', models.ForeignKey(blank=True, help_text='Seteado = privada de este usuario (siempre junto con partitura). Vacío = de obra o de parte.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anotaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anotación',
                'verbose_name_plural': 'Anotaciones',
                'ordering': ['compas'],
            },
        ),
    ]
