# Generated by Django 6.0.6 on 2026-07-30 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partituras', '0042_anotacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='efectotempo',
            name='tipo',
            field=models.CharField(choices=[('accelerando', 'Accelerando'), ('ritardando', 'Rallentando'), ('calderon', 'Calderón'), ('pausa', 'Pausa')], max_length=12),
        ),
    ]
