# Generated by Django 6.0.6 on 2026-07-30 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partituras', '0043_alter_efectotempo_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='anotacion',
            name='offset_x',
            field=models.FloatField(blank=True, help_text='Vacío = anclada al compás (arriba/abajo, se acomoda sola sin superponerse con otras). Seteado junto con offset_y = anclada a un punto exacto dentro de la caja del compás (fracción 0-1 de su ancho) — para marcar una nota puntual, sin acomodo automático: el punto lo elige el usuario, a propósito. Se define sólo al crearla, no cambia después.', null=True),
        ),
        migrations.AddField(
            model_name='anotacion',
            name='offset_y',
            field=models.FloatField(blank=True, help_text='Ver offset_x — fracción 0-1 del alto de la caja del compás.', null=True),
        ),
    ]
