# Generated by Django 6.0.6 on 2026-07-31 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partituras', '0044_anotacion_offset_x_anotacion_offset_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='enlace',
            field=models.URLField(blank=True, help_text='Link opcional a la fuente de la grabación de referencia (video, página, etc.).', max_length=500, verbose_name='Enlace'),
        ),
        migrations.AddField(
            model_name='obra',
            name='version',
            field=models.CharField(blank=True, help_text='Quién toca en la grabación de referencia (texto libre, opcional).', max_length=200, verbose_name='Versión'),
        ),
    ]
