# Generated by Django 6.0.6 on 2026-08-08 01:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partituras', '0045_obra_enlace_obra_version'),
        ('usuarios', '0003_grupo_usuario_mirror'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='restriccion',
            field=models.CharField(choices=[('hereda', 'Hereda del repertorio'), ('publica', 'Pública (todos los usuarios logueados)'), ('restringida', 'Restringida a grupos/usuarios puntuales')], default='hereda', help_text="Sólo importa si la obra está publicada. 'Hereda' usa los grupos_visibles del Repertorio de su Ciclo (o público si no tiene Ciclo, o si el repertorio no tiene grupos configurados). 'Restringida' sólo puede ACOTAR lo que el repertorio ya permitía, nunca ampliarlo — para el caso contrario (una obra puntual que debe verse igual aunque su repertorio esté restringido) usar 'Pública'.", max_length=12),
        ),
        migrations.AddField(
            model_name='obra',
            name='usuarios_visibles',
            field=models.ManyToManyField(blank=True, help_text="Sólo se usa con restriccion='restringida' — para casos puntuales (p.ej. un invitado que no pertenece a ninguno de los grupos_visibles).", related_name='obras_visibles_individual', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ObraGrupoVisible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupousuario', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='usuarios.grupousuario')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partituras.obra')),
            ],
            options={
                'unique_together': {('obra', 'grupousuario')},
            },
        ),
        migrations.AddField(
            model_name='obra',
            name='grupos_visibles',
            field=models.ManyToManyField(blank=True, help_text="Sólo se usa con restriccion='restringida'.", related_name='obras_restringidas', through='partituras.ObraGrupoVisible', to='usuarios.grupousuario'),
        ),
        migrations.CreateModel(
            name='RepertorioGrupoVisible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupousuario', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='usuarios.grupousuario')),
                ('repertorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partituras.repertorio')),
            ],
            options={
                'unique_together': {('repertorio', 'grupousuario')},
            },
        ),
        migrations.AddField(
            model_name='repertorio',
            name='grupos_visibles',
            field=models.ManyToManyField(blank=True, help_text='Si está vacío, el repertorio es visible para cualquier usuario logueado (comportamiento de siempre). Si tiene grupos, sólo esos grupos ven sus obras (además del dueño de cada una y los admins, que siempre ven todo) — ver Obra.restriccion para excepciones puntuales dentro del repertorio.', related_name='repertorios_visibles', through='partituras.RepertorioGrupoVisible', to='usuarios.grupousuario'),
        ),
    ]
