# Generated by Django 6.0.6 on 2026-08-20 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partituras', '0046_repertorio_obra_visibilidad_grupos'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferenciaobra',
            name='compases_al_aire_en_loop',
            field=models.BooleanField(default=False, help_text='Si el loop está activo y hay compases_al_aire configurados, repetir la cuenta de entrada en cada vuelta (no sólo al arrancar) — apagado por default: en un pasaje que ya se domina, la cuenta en cada vuelta interrumpe más de lo que ayuda.'),
        ),
    ]
