# Generated by Django 6.0.6 on 2026-07-17 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20)),
                ('tipo', models.CharField(blank=True, choices=[('error', 'Error'), ('idea', 'Idea'), ('duda', 'Duda'), ('comentario', 'Comentario')], max_length=20)),
                ('texto', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comentarios_versiones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'db_table': 'sc_versiones_comentario',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='PerfilVersiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultima_version_vista', models.CharField(blank=True, default='', max_length=20)),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_versiones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de versiones',
                'verbose_name_plural': 'Perfiles de versiones',
                'db_table': 'sc_versiones_perfil',
            },
        ),
    ]
